name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.x'

      - name: Install dependencies (workspaces)
        run: bun install

      - name: Run backend tests (if any)
        working-directory: backend
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          files=(**/*.test.ts **/*.test.tsx **/*.test.js **/*.test.jsx)
          if [ ${#files[@]} -gt 0 ]; then
            echo "Found ${#files[@]} backend test files"
            bun test
          else
            echo "No backend tests found; skipping."
          fi

      - name: Run frontend tests (if any)
        working-directory: frontend
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          files=(**/*.test.ts **/*.test.tsx **/*.test.js **/*.test.jsx)
          if [ ${#files[@]} -gt 0 ]; then
            echo "Found ${#files[@]} frontend test files"
            bun test
          else
            echo "No frontend tests found; skipping."
          fi